<Project Sdk="Microsoft.NET.Sdk.WebAssembly">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RuntimeIdentifier>browser-wasm</RuntimeIdentifier>
    <OutputType>Exe</OutputType>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>false</IsPackable>
    <WasmMainJSPath>wwwroot/index.js</WasmMainJSPath>
    <SupportedOSPlatformVersion>0.0</SupportedOSPlatformVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DocxportNet\DocxportNet.csproj" />
    <Content Include="..\LICENSE" Link="wwwroot\LICENSE" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
